defaults:
  - data: custom_signal
  - optimizer: adamW
  - trainer: default_trainer
  - extractor : ConvFeatureExtractor_signal
  - masker : MultiBlock
  - _self_

model: JEPA
save_dir: 'outputs'
seed: 42
